// Builds every derived logo file from the exact master artwork, so they can be regenerated at any time:
//
//   npm run brand:build -w @g12/web
//
// Master (never edited by this script):   public/brand/g12-news-logo.jpg   (1254 x 1254, the supplied artwork)
//                                         public/brand/g12-news-logo.svg   (the supplied SVG, same artwork embedded)
// Derived (no recolouring, redrawing or re-tracing of the logo):
//   public/brand/g12-news-logo-white.png   the same artwork on a true white backdrop (see white-backdrop.mjs:
//                                          the logo's pixels are unchanged; only the grey backdrop is lifted)
//   public/brand/g12-news-logo-crop.<hash>.png  that, cropped with a small margin: header and footer
//                                          (src/lib/brand.generated.ts records the current file name)
//   public/brand/g12-news-placeholder.jpg  16:10 card for stories that have no image (grey original backdrop)
//   src/app/icon.jpg, apple-icon.jpg       browser tab / home-screen icons
//   src/app/opengraph-image.jpg            link-preview image (WhatsApp, Facebook, X)
import { createHash } from "node:crypto";
import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { onWhite } from "./white-backdrop.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const master = resolve(root, "public/brand/g12-news-logo.jpg");
const whiteMaster = resolve(root, "public/brand/g12-news-logo-white.png");

// Where the artwork sits inside the 1254 x 1254 master (measured from its pixels): the logo itself is
// x 114-1174, y 295-982; its soft drop shadow fades out by y ~1160.
const LOGO_CENTER = { x: 644, y: 638 };
const CROP_WHITE = { left: 84, top: 272, width: 1130, height: 858 }; // tight: on white the margin is invisible
const CROP_GREY = { left: 46, top: 239, width: 1188, height: 931 }; // roomy: the backdrop is part of the picture

const out = (path) => resolve(root, path);
const write = async (image, path, format = "png") => {
  await mkdir(dirname(out(path)), { recursive: true });
  const info = await (format === "jpg" ? image.jpeg({ quality: 90, mozjpeg: true }) : image.png({ compressionLevel: 9 })).toFile(out(path));
  console.log(`${path.padEnd(42)} ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
};

// 0. The artwork on a white backdrop.
const white = await onWhite(master);
await write(sharp(white.data, { raw: { width: white.width, height: white.height, channels: 3 } }), "public/brand/g12-news-logo-white.png");

// 1. Header / footer logo (lossless). The file name carries a hash of its content, so when the logo
//    changes its URL changes too, and browsers, CDNs and Next's image cache never serve a stale copy.
const crop = await sharp(whiteMaster).extract(CROP_WHITE).png({ compressionLevel: 9 }).toBuffer({ resolveWithObject: true });
const hash = createHash("sha256").update(crop.data).digest("hex").slice(0, 8);
const cropName = `g12-news-logo-crop.${hash}.png`;
for (const old of await readdir(out("public/brand"))) if (/^g12-news-logo-crop\..+\.png$/.test(old) && old !== cropName) await unlink(out(`public/brand/${old}`));
await writeFile(out(`public/brand/${cropName}`), crop.data);
console.log(`${`public/brand/${cropName}`.padEnd(42)} ${crop.info.width}x${crop.info.height}  ${(crop.info.size / 1024).toFixed(0)} KB`);
await writeFile(
  out("src/lib/brand.generated.ts"),
  `// Generated by scripts/brand-assets.mjs (npm run brand:build -w @g12/web). Do not edit by hand.\n` +
    `export const LOGO_CROP = { src: "/brand/${cropName}", width: ${crop.info.width}, height: ${crop.info.height} } as const;\n`,
);
console.log("src/lib/brand.generated.ts".padEnd(42), "->", cropName);

// 2. Placeholder card: the logo, smaller, centred on its own grey backdrop, which is continued outward
//    by repeating the edge pixels so there is no visible seam.
const placeholderLogo = await sharp(master).extract(CROP_GREY).resize({ height: 400 }).toBuffer({ resolveWithObject: true });
await write(
  sharp(placeholderLogo.data).extend({
    top: Math.floor((750 - placeholderLogo.info.height) / 2),
    bottom: Math.ceil((750 - placeholderLogo.info.height) / 2),
    left: Math.floor((1200 - placeholderLogo.info.width) / 2),
    right: Math.ceil((1200 - placeholderLogo.info.width) / 2),
    extendWith: "copy",
  }),
  "public/brand/g12-news-placeholder.jpg",
  "jpg",
);

// 3. Square icons, centred on the logo (white backdrop).
const SIDE = 1100;
const squareIcon = () =>
  sharp(whiteMaster).extract({ left: LOGO_CENTER.x - SIDE / 2, top: LOGO_CENTER.y - SIDE / 2, width: SIDE, height: SIDE });
await write(squareIcon().resize(512, 512), "src/app/icon.jpg", "jpg");
await write(squareIcon().resize(180, 180), "src/app/apple-icon.jpg", "jpg");

// 4. Link-preview image (1200 x 630): the logo centred on white.
const og = await sharp(whiteMaster).extract(CROP_WHITE).resize({ height: 500 }).toBuffer({ resolveWithObject: true });
await write(
  sharp(og.data).extend({
    top: Math.floor((630 - og.info.height) / 2),
    bottom: Math.ceil((630 - og.info.height) / 2),
    left: Math.floor((1200 - og.info.width) / 2),
    right: Math.ceil((1200 - og.info.width) / 2),
    background: "#ffffff",
  }),
  "src/app/opengraph-image.jpg",
  "jpg",
);
