// Generated by scripts/brand-assets.mjs (npm run brand:build -w @g12/web). Do not edit by hand.
export const LOGO_CROP = { src: "/brand/g12-news-logo-crop.da1ec8b4.png", width: 1130, height: 858 } as const;
